# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playcallplayerstat',
            name='play_call_stat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.PlayCallStat'),
            preserve_default=False,
        ),
    ]
