# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playcallplayerstat_play_call_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='playcallstat',
            name='code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
