# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playcallstat_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('code', models.CharField(default=None, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.PlayerPosition'),
            preserve_default=False,
        ),
    ]
