# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170113_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='playcallplayer',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.PlayerPosition'),
            preserve_default=False,
        ),
    ]
