# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playcallplayer_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_name_name',
            new_name='last_name',
        ),
    ]
