# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170113_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('short_name', models.CharField(default=None, max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('short_name', models.CharField(default=None, max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('short_name', models.CharField(default=None, max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.League'),
        ),
        migrations.AddField(
            model_name='conference',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Conference'),
            preserve_default=False,
        ),
    ]
