# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170122_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playcall',
            name='purs',
        ),
        migrations.RemoveField(
            model_name='playcall',
            name='tech',
        ),
        migrations.AddField(
            model_name='playcallplayer',
            name='purs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playcallplayer',
            name='tech',
            field=models.BooleanField(default=False),
        ),
    ]
