# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170122_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
