# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=0, help_text='In Inches'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
