# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170123_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playcallplayer',
            name='purs',
            field=models.IntegerField(choices=[(-1, '+'), (1, '-')], default=0),
        ),
        migrations.AlterField(
            model_name='playcallplayer',
            name='tech',
            field=models.IntegerField(choices=[(-1, '+'), (1, '-')], default=0),
        ),
    ]
