# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170123_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='playcallplayer',
            name='purs',
            field=models.IntegerField(choices=[(0, '-'), (1, '+')], default=0),
        ),
        migrations.AlterField(
            model_name='playcallplayer',
            name='tech',
            field=models.IntegerField(choices=[(0, '-'), (1, '+')], default=0),
        ),
        migrations.AlterField(
            model_name='playcallplayerstat',
            name='score',
            field=models.IntegerField(choices=[(0, ''), (1, '+'), (-1, '-'), (2, '++'), (-2, '--'), (3, '+++'), (-3, '---'), (4, '++++'), (-4, '----'), (5, '+++++'), (-5, '-----'), (6, '++++++'), (-6, '------')], default=0),
        ),
    ]
